travis:
  secure:
    BINSTAR_TOKEN: KVGDZ6HnYMKQN5nx4uBAysjmuAwsED+BrReWo6ML8Kd0sfnanyxi73v0Oya3FvYj9g2k2QaNNzxz4UJwDvU17/Pe4d0BlSpa5tO/ETwxajODdqdvNKVwAzd27jgGyXU6tMl+vatzwreBkqj2y2gZfOZS0fKgYZ29RLo4M9keU63JZS6EWkv3R+diQku7o9laxxPAW/V0bgIa2ABWSTTsqKz+kM5TtTH0S1QFWWHKm7vJYr5dG381tx3Y3pbsfQPEFDm/bptbFQ+dVNb2KQD53EQOMAMK+rAsMosfX8BY+a5bdJT3vSvH5CBWraiWr/vMhs/XDSRF1mH97pDXDd61vXsSChbWmvX1KfyeMnRbKmkg8F0B4+3WRiNi9n4PXHhCH7GtkjzarkCmVtBoATSpiP1eoF7oC8NAZXVPeK3POyYGXS6gcCdbFqOXPhdOlJh3aROyzQRd/0YrgumN0uy+cMdRoGaYjspop8Xd2+Rhq/et+30SOX99mwfsk2mRtOwxwsag5DQ+RTzlf2pbOBtVY3X0TVs6mqMEaFpHjXrdY43Pb1Itkc1B7fmHmMMVJOLDNX0PZACHSd17k9DZefL25wqSFsFCJadM+QvSbBGjadAj2LUAU8PKilWfOXGlwG1jOtuRzkhN1QoKldmKgDailiMfgYElGRsqdix3d20/9Dw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
